// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQZfcsCIWOvb82zbQrBRVpa1IyDmq7yw',
    appId: '1:278865944046:web:d8434850e488e398be42ff',
    messagingSenderId: '278865944046',
    projectId: 'spotify01-7003d',
    authDomain: 'spotify01-7003d.firebaseapp.com',
    storageBucket: 'spotify01-7003d.firebasestorage.app',
    measurementId: 'G-ZQ8MFTCF65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGt8GR6a1UqOg18l0lzXMTnnMLwE9WAsk',
    appId: '1:278865944046:android:9b4e13d9868ad74abe42ff',
    messagingSenderId: '278865944046',
    projectId: 'spotify01-7003d',
    storageBucket: 'spotify01-7003d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB26PPWu7fVYwUUeBvZnPykYnGirzj9ro',
    appId: '1:278865944046:ios:e33511758e12d7e2be42ff',
    messagingSenderId: '278865944046',
    projectId: 'spotify01-7003d',
    storageBucket: 'spotify01-7003d.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB26PPWu7fVYwUUeBvZnPykYnGirzj9ro',
    appId: '1:278865944046:ios:e33511758e12d7e2be42ff',
    messagingSenderId: '278865944046',
    projectId: 'spotify01-7003d',
    storageBucket: 'spotify01-7003d.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSQZfcsCIWOvb82zbQrBRVpa1IyDmq7yw',
    appId: '1:278865944046:web:cd92ec7681289364be42ff',
    messagingSenderId: '278865944046',
    projectId: 'spotify01-7003d',
    authDomain: 'spotify01-7003d.firebaseapp.com',
    storageBucket: 'spotify01-7003d.firebasestorage.app',
    measurementId: 'G-RL3E5NDXXP',
  );
}
